"""Add AI tracking tables

Revision ID: 58c95a9d863b
Revises: 0003_vocabulary_items
Create Date: 2026-06-01 20:21:44.979394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58c95a9d863b'
down_revision: Union[str, None] = '0003_vocabulary_items'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_cache',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('context_hash', sa.String(), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_cache_cache_key'), 'ai_cache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_ai_cache_id'), 'ai_cache', ['id'], unique=False)
    op.create_table('ai_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('input_token_estimate', sa.Integer(), nullable=True),
    sa.Column('output_token_estimate', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_requests_id'), 'ai_requests', ['id'], unique=False)
    op.create_table('ai_user_consent',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('allow_send_selected_text', sa.Boolean(), nullable=True),
    sa.Column('allow_send_page_context', sa.Boolean(), nullable=True),
    sa.Column('allow_send_notes', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_ai_user_consent_user_id'), 'ai_user_consent', ['user_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_refs_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_ai_user_consent_user_id'), table_name='ai_user_consent')
    op.drop_table('ai_user_consent')
    op.drop_index(op.f('ix_ai_requests_id'), table_name='ai_requests')
    op.drop_table('ai_requests')
    op.drop_index(op.f('ix_ai_cache_id'), table_name='ai_cache')
    op.drop_index(op.f('ix_ai_cache_cache_key'), table_name='ai_cache')
    op.drop_table('ai_cache')
    # ### end Alembic commands ###
